CREATE TABLE IF NOT EXISTS message(
 id SERIAL PRIMARY KEY,
 type VARCHAR NOT NULL,
 date TIMESTAMP NOT NULL,
 date_unixtime BIGINT NOT NULL,
 edited TIMESTAMP NOT NULL,
 edited_unixtime BIGINT NOT NULL,
 "from" VARCHAR NOT NULL,
 from_id VARCHAR NOT NULL,
 text VARCHAR NOT NULL
);